#Server Config
server:
    port: 8080
    undertow:
      accesslog:
        enabled: true
        rotate: true
        dir: /apprun/logs/bob-learn/
      io-threads: 8
      direct-buffers: true
      buffer-size: 1024

#Spring Config
